# Generated by Django 3.2.8 on 2022-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('primerapellido', models.TextField(max_length=50)),
                ('segundoapellido', models.TextField(max_length=50)),
            ],
        ),
    ]
