# Generated by Django 3.2.8 on 2022-05-20 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('showcaseImage', models.ImageField(upload_to='Images/')),
                ('dateTimeOfCreation', models.DateTimeField(auto_now=True)),
                ('shareURL', models.URLField()),
                ('likes', models.IntegerField()),
                ('disLikes', models.IntegerField()),
                ('bookmarks', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
